INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(1, 'Hector', 'Núñez', 'hector.nunez.05@gmail.com','2018-03-01','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(2, 'Federico', 'Illane', 'fillane@gmail.com','2018-03-01','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(3, 'Leandro', 'Medin', 'lmedin@metrogas.com.ar','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(4, 'Rances Daniel', 'Peña Ochoa', 'rances_daniel@gmail.com','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(5, 'Silvia Carolina', 'Paredes', 'caro_paredes@outlook.com','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(6, 'Andresito', 'Segovia', 'andres_segovia@outlook.com','2018-03-05','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(7, 'Hector', 'Núñez', 'hector.nunez.05@gmail.com','2018-03-01','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(8, 'Federico', 'Illane', 'fillane@gmail.com','2018-03-01','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(9, 'Leandro', 'Medin', 'lmedin@metrogas.com.ar','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(10, 'Rances Daniel', 'Peña Ochoa', 'rances_daniel@gmail.com','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(11, 'Silvia Carolina', 'Paredes', 'caro_paredes@outlook.com','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(12, 'Andresito', 'Segovia', 'andres_segovia@outlook.com','2018-03-05','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(13, 'Hector', 'Núñez', 'hector.nunez.05@gmail.com','2018-03-01','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(14, 'Federico', 'Illane', 'fillane@gmail.com','2018-03-01','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(15, 'Leandro', 'Medin', 'lmedin@metrogas.com.ar','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(16, 'Rances Daniel', 'Peña Ochoa', 'rances_daniel@gmail.com','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(17, 'Silvia Carolina', 'Paredes', 'caro_paredes@outlook.com','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(18, 'Andresito', 'Segovia', 'andres_segovia@outlook.com','2018-03-05','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(19, 'Hector', 'Núñez', 'hector.nunez.05@gmail.com','2018-03-01','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(20, 'Federico', 'Illane', 'fillane@gmail.com','2018-03-01','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(21, 'Leandro', 'Medin', 'lmedin@metrogas.com.ar','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(22, 'Rances Daniel', 'Peña Ochoa', 'rances_daniel@gmail.com','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(23, 'Silvia Carolina', 'Paredes', 'caro_paredes@outlook.com','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(24, 'Andresito', 'Segovia', 'andres_segovia@outlook.com','2018-03-05','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(25, 'Hector', 'Núñez', 'hector.nunez.05@gmail.com','2018-03-01','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(26, 'Federico', 'Illane', 'fillane@gmail.com','2018-03-01','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(27, 'Leandro', 'Medin', 'lmedin@metrogas.com.ar','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(28, 'Rances Daniel', 'Peña Ochoa', 'rances_daniel@gmail.com','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(29, 'Silvia Carolina', 'Paredes', 'caro_paredes@outlook.com','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(30, 'Andresito', 'Segovia', 'andres_segovia@outlook.com','2018-03-05','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(31, 'Hector', 'Núñez', 'hector.nunez.05@gmail.com','2018-03-01','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(32, 'Federico', 'Illane', 'fillane@gmail.com','2018-03-01','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(33, 'Leandro', 'Medin', 'lmedin@metrogas.com.ar','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(34, 'Rances Daniel', 'Peña Ochoa', 'rances_daniel@gmail.com','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(35, 'Silvia Carolina', 'Paredes', 'caro_paredes@outlook.com','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(36, 'Andresito', 'Segovia', 'andres_segovia@outlook.com','2018-03-05','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(37, 'Hector', 'Núñez', 'hector.nunez.05@gmail.com','2018-03-01','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(38, 'Federico', 'Illane', 'fillane@gmail.com','2018-03-01','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(39, 'Leandro', 'Medin', 'lmedin@metrogas.com.ar','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(40, 'Rances Daniel', 'Peña Ochoa', 'rances_daniel@gmail.com','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(41, 'Silvia Carolina', 'Paredes', 'caro_paredes@outlook.com','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(42, 'Andresito', 'Segovia', 'andres_segovia@outlook.com','2018-03-05','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(43, 'Hector', 'Núñez', 'hector.nunez.05@gmail.com','2018-03-01','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(44, 'Federico', 'Illane', 'fillane@gmail.com','2018-03-01','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(45, 'Leandro', 'Medin', 'lmedin@metrogas.com.ar','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(46, 'Rances Daniel', 'Peña Ochoa', 'rances_daniel@gmail.com','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(47, 'Silvia Carolina', 'Paredes', 'caro_paredes@outlook.com','2018-03-02','');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(48, 'Andresito', 'Segovia', 'andres_segovia@outlook.com','2018-03-05','');